### ISSUE TITLE
Error loading Craft dashboard

### ISSUE THREAD

**Issue by AndrewMac** [ournameismud/currency-layer#6] opened 2020-11-09 01:07 UTC
Hello again, and thanks making those updates recently. Things are again working great, except for one thing. Although everything works fine on my local development site, I get an error on the main Dashboard page on my production site. All of the other pages I've checked so far seem to work just fine, so it's just the dashboard page (site.url/admin).

I tracked the problem down to capitalisation in the src/assetbundles directory. If the 'CurrencyLayer' folder is set to lowercase ('currencylayer') my dashboard works again. But obviously, (a) I don't know if this would cause issues for anyone else, and (b) I don't want to keep having to change things manually in a composer-based deployment system.

I really do hope your health is back on track again, and if it is then I hope you don't mind taking a teensy little bit more time to look into this, to see if it's a change you could make.

Thanks again for all your help, Andrew

Here's the error, by the way:

ReflectionException: Class ournameismud\currencylayer\assetbundles\currencylayer\CurrencyLayerAsset does not exist in /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php:453
Stack trace:
#0 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php(453): ReflectionClass->__construct()
#1 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php(380): yii\di\Container->getDependencies()
#2 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#3 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#4 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/AssetManager.php(264): yii\BaseYii::createObject()
#5 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/AssetManager.php(237): yii\web\AssetManager->loadBundle()
#6 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle()
#7 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle()
#8 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/helpers/Template.php(92): twig_get_attribute()
#9 /home/forge/website.com/releases/20201108223808/storage/runtime/compiled_templates/58/586cb5751c2bed0476779e665cb4700342ec6c3f67efcc062709f9b488c13946.php(46): craft\helpers\Template::attribute()
#10 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Template.php(405): __TwigTemplate_399a49d6d9221ec986bfc0211d3e197261bebde53f8e868305196b72de65efc0->doDisplay()
#11 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#12 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#13 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#14 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#15 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render()
#16 /home/forge/website.com/releases/20201108223808/vendor/ournameismud/currency-layer/src/widgets/Currency.php(91): craft\web\View->renderTemplate()
#17 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/controllers/DashboardController.php(80): ournameismud\currencylayer\widgets\Currency->getSettingsHtml()
#18 [internal function]: craft\controllers\DashboardController->actionIndex()
#19 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#20 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#21 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#22 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#23 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#24 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#25 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#26 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#27 /home/forge/website.com/releases/20201108223808/web/index.php(21): yii\base\Application->run()
#28 {main}

Next yii\base\InvalidConfigException: Failed to instantiate component or class "ournameismud\currencylayer\assetbundles\currencylayer\CurrencyLayerAsset". in /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php:455
Stack trace:
#0 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php(380): yii\di\Container->getDependencies()
#1 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#2 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#3 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/AssetManager.php(264): yii\BaseYii::createObject()
#4 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/AssetManager.php(237): yii\web\AssetManager->loadBundle()
#5 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle()
#6 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle()
#7 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/helpers/Template.php(92): twig_get_attribute()
#8 /home/forge/website.com/releases/20201108223808/storage/runtime/compiled_templates/58/586cb5751c2bed0476779e665cb4700342ec6c3f67efcc062709f9b488c13946.php(46): craft\helpers\Template::attribute()
#9 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Template.php(405): __TwigTemplate_399a49d6d9221ec986bfc0211d3e197261bebde53f8e868305196b72de65efc0->doDisplay()
#10 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#11 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#12 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#13 /home/forge/website.com/releases/20201108223808/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#14 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render()
#15 /home/forge/website.com/releases/20201108223808/vendor/ournameismud/currency-layer/src/widgets/Currency.php(91): craft\web\View->renderTemplate()
#16 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/controllers/DashboardController.php(80): ournameismud\currencylayer\widgets\Currency->getSettingsHtml()
#17 [internal function]: craft\controllers\DashboardController->actionIndex()
#18 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#20 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#21 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#22 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#23 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#24 /home/forge/website.com/releases/20201108223808/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#25 /home/forge/website.com/releases/20201108223808/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#26 /home/forge/website.com/releases/20201108223808/web/index.php(21): yii\base\Application->run()
#27 {main}

**Comment by cole007** [comment] 2020-11-09 08:57
Hi @AndrewMac 

The capitalisation was due to an issue with Composer 2 incompatibility.
As a result I had to rename the folder/file accordingly.

Bit of a long shot but could you possibly uninstall then reinstall to see if that fixes the problem again?

**Comment by cole007** [comment] 2020-11-09 19:57
Hi @AndrewMac 

I have tested installing on a new, local build with no problems (Mac OS X with Craft 3.5.15.1, PHP 7.3.7, MySQL 5.7.26).
Could you let me know what version of Craft you are using, what other plugins you have installed, OS and versions of PHP and MySQL please?

**Comment by cole007** [comment] 2020-11-09 19:58
(also the version of the Currency Layer plugin you are using?)

**Comment by cole007** [comment] 2020-12-04 12:51
Belated hi @AndrewMac  - sorry but just identified the cause of the issue which seems to be around case sensitivity on Linux servers that could not be detected locally on Mac.

Have released a hotfix removing the widget from the primary plugin class until I can figure out the solution to this problem (the widget was not even in use so not quite sure how it ended up in the release).

Closing this ticket and hopefully fixes the problem you've been experiencing but please comment if not.

**Closed as completed by cole007** 2020-12-04 12:51 UTC

**Comment by AndrewMac** [comment] 2020-12-05 02:36
Hi Cole

Thanks for that. I'm glad you got it sorted out. I've been busy, but I found a temporary workaround in running a script on the server that renamed the file to lowercase. Good to know that I can take that out now.

I didn't actually even realise there was a dashboard widget, but if you ever have time to get that working it would be fantastic, as (I assume) it would perhaps allow our users to check, and/or maybe update, the current exchange rates? Which would be great.

Even without that, however, thanks so much for your work on this great plugin. Hope your health issues have all been resolved, too!

Kind regards
Andrew Mac
